steps:
  # 1. Build Backend Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-east4-docker.pkg.dev/$PROJECT_ID/pace-docker/pace-backend:latest'
      - '.'

  # 2. Push Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east4-docker.pkg.dev/$PROJECT_ID/pace-docker/pace-backend:latest']

  # 3. Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'pace-backend'
      - '--image'
      - 'us-east4-docker.pkg.dev/$PROJECT_ID/pace-docker/pace-backend:latest'
      - '--region'
      - 'us-east4'
      - '--allow-unauthenticated'

images:
  - 'us-east4-docker.pkg.dev/$PROJECT_ID/pace-docker/pace-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
